name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: npm i
      - run: npm run build
      - run: git config --global user.name "PromiSe####"
      - run: git config --global user.email "vicimpa@ya.ru"
      - run: npm version $GITHUB_REF_NAME -f

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public 
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
